# Generated by Django 5.1.1 on 2024-09-11 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_coder', '0003_entregable_profesor'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='profesion',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
